name: Auto PR for syncing master to master-private

on:
  push:
    branches: [master]

jobs:
  auto-pr-for-branch-syncing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync branches
        if: github.repository == 'omisego/plasma-contracts-private'
        uses: TreTuna/sync-branches@1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: master
          TO_BRANCH: master-private
