name: Dispatch sync event to plasma-contracts-private

on:
  push:
    branches: [master]

jobs:
  dispatch-sync-event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Repository Dispatch
        if: github.repository == 'omisego/plasma-contracts'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.HOUSE_KEEPER_BOT_TOKEN }}
          repository: omisego/plasma-contracts-private
          event-type: sync-from-public
          client-payload: '{"sha": "${{ github.sha }}"}'
