name: Sync with plasma-contracts

on:
  repository_dispatch:
    types: [sync-from-public]

jobs:
  sync-public-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # use personal token to continue GH action workflows
          # by default GH would not trigger another workflow if it is from GH action token
          # see: https://github.com/ad-m/github-push-action/issues/32
          token: ${{ secrets.HOUSE_KEEPER_BOT_TOKEN }}
      - name: Event Information
        run: |
          echo "Syncing with sha '${{ github.event.client_payload.sha }}'"
      - name: GitHub Repo Sync
        uses: repo-sync/github-sync@v2.0.0
        with:
          source_repo: omisego/plasma-contracts
          source_branch: master
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
